name: "🧑‍💻 Internal: Dev Task"
description: Only use this issue type if you are a maintainer or collaborator of OctoPrint!
title: "[Task] "
labels: ["task"]
body:
  - type: textarea
    validations:
      required: true
  - type: checkboxes
    attributes:
      options:
        - label: I'm a maintainer or collaborator of OctoPrint and allowed to use this issue type
          required: true
